### ISSUE TITLE
Issue importing kind-of dependancy

### ISSUE THREAD

**Issue by mileshenley** [jonschlinkert/is-descriptor#3]
Hey,

I am actually trying to use karma-server-side module with karma, and i am running into some issue with the 'is-descriptor' dependency importing kind-of. I am not sure if this is a bug or an issue with my configuration, but any help would be greatly appreciated. 

here is the failure output.
Cannot find module 'kind-of'.
    Simple.test.js:8902:88
    webpackContextResolve@Simple.test.js:8902:90
    webpackContext@Simple.test.js:8899:51
    getter@Simple.test.js:8670:32
    isDescriptor@Simple.test.js:8588:13
    defineProperty@Simple.test.js:8559:20
    hiddens@Simple.test.js:8524:14
    parseFunction@Simple.test.js:8466:18
    run@Simple.test.js:8390:26
    Simple.test.js:56:20

here is a reduced version of the setup i am using.

tools/
        webpack.shared.config.js
src/
        Simple.test.js
package.json
karma.conf.json

package.json
```javascript
{
  "description": "",
  "scripts": {
    "test": "karma start karma.conf.js --single-run",
    "test:debug": "karma start karma.conf.js --browsers=Chrome --single-run=false"
  },
  "keywords": [],
  "devDependencies": {
    "autoprefixer": "^6.3.7",
    "babel-core": "^6.10.4",
    "babel-loader": "^6.2.4",
    "babel-plugin-add-module-exports": "^0.2.1",
    "babel-plugin-transform-runtime": "^6.9.0",
    "babel-polyfill": "^6.16.0",
    "babel-preset-es2015": "^6.16.0",
    "babel-preset-react": "^6.16.0",
    "chai": "^3.5.0",
    "karma": "^1.3.0",
    "karma-chrome-launcher": "^2.0.0",
    "karma-cli": "^1.0.1",
    "karma-mocha": "^1.1.1",
    "karma-mocha-reporter": "^2.2.0",
    "karma-phantomjs-launcher": "^1.0.1",
    "karma-server-side": "^1.5.0",
    "karma-webpack": "^1.7.0",
    "mocha": "^3.1.2",
    "postcss-loader": "^0.11.1",
    "precss": "^1.4.0",
    "webpack": "^1.13.1"
  },
  "dependencies": {
    "babel-runtime": "^6.11.6"
  }
}
```

karma.conf.json
```javascript
// Karma configuration
const path = require('path');
const webpackConfig = require('./tools/webpack.shared.config');
const extend = require('extend');

module.exports = (config) => {
    config.set({
        basePath: 'src',
        frameworks: ['mocha', 'server-side'],
        files: [
            '**/Simple.test.js',
        ],
        exclude: [],
        preprocessors: {
            '**/*.test.js': ['webpack'],
        },
        reporters: ['mocha'],
        port: 9876,
        colors: true,
        logLevel: config.LOG_INFO,
        autoWatch: true,
        browsers: ['PhantomJS'],
        singleRun: false,
        concurrency: 1,
        webpack: webpackConfig,
    });
};
```

webpack.shared.config.js
```javascript
const path = require('path');
const webpack = require('webpack');
const plugins = [];

if (process.env.NODE_ENV) {
    plugins.push(new webpack.optimize.UglifyJsPlugin());
}

module.exports = {
    resolve: {
        extensions: ['', '.js', '.jsx', '.json'],
    },
    module: {
        loaders: [{
            test: /\.js?$/,
            exclude: /node_modules/,
            loaders: [
                'babel-loader?cacheDirectory&presets[]=es2015&plugins[]=transform-runtime',
            ],
        }],
    },
    plugins,
};
```

Simple.test.js
```javascript
/* eslint-env mocha */
import { assert } from 'chai';

const server = require('karma-server-side');

describe('Test send request', () => {
    it('karma-server-side test', (done) => {
        const server = require('karma-server-side');
        server.run(() => {
            return 'success';
        }).then((result) => {
            assert.equal(result, 'success');
            done();
        });
    });
});
```

the workflow i am running is just to run the following commands
'npm install'
'npm test'

additionally i do see these warnings:
WARNING in ./~/is-descriptor/utils.js
Critical dependencies:
7:34-41 require function is used in a way in which dependencies cannot be statically extracted
 @ ./~/is-descriptor/utils.js 7:34-41

WARNING in ./~/is-descriptor/package.json
Module parse failed: /Users/mhenley/git/scrd/milestest/node_modules/is-descriptor/package.json Unexpected token (2:9)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (2:9)

Any ideas? could this be a bug? or am i just doing something wrong?

Thanks!

**Comment by jonschlinkert** [comment]
Hi, thanks for the detailed description. This is actually a known bug in webpack. I believe [this webpack loader](https://github.com/doowb/unlazy-loader) is a solution for this bug.

(Webpack doesn't use node's native require system for resolving packages, it uses a custom implementation that doesn't have 100% parity with node.js. so edge cases like this seem to crop up pretty often)

hope that helps

**Comment by mileshenley** [comment]
Thanks that definitely fixed my issue.

i really appreciate the quick response! Thanks!

**Comment by jonschlinkert** [comment]
great, glad to hear it! thanks for reporting back!
