### ISSUE TITLE
0.1.6 tag is missing on github

### ISSUE THREAD

**Issue by mdelamere** [jonschlinkert/is-descriptor#9]
Hi,

in our company we are using 0.1.6 and I can see that version on npmjs. However, for some reason the 0.1.6 to has not been set in git. In fact when I look at the commits for 1.0.0 I can see that the version jumped directly from 0.1.5 to 1.0.0. How come there appears to be some mismatch? This is causing an issue in our licensing department. Is it possible to add that tag retrospectively?

Any help on this would be greatly appreciated.

Thanks!
Michael

**Comment by emtege** [comment]
Hi there,
we are running into the same problem regarding the opensource office. 

@mdelamere how did you solve this issue?
@jonschlinkert could you pinpoint us to the commit hash that resulted in the 0.1.6 version?

Thanks in advance for your energy and investment.

Kind Regards
Matthias

**Comment by AmeyaLokre** [comment]
Hello,

We are running into the same issue.

@mdelamere @emtege how were you able to solve this issue ?
@jonschlinkert as mentioned by @emtege , can you point to the commit hash for the 0.1.6 version ?

Thank you,
Ameya

**Comment by ljharb** [comment]
It's not the original commit, but I've reconstructed it with the published version timestamp and committer attribution based on https://diff.intrinsic.com/is-descriptor/0.1.5/0.1.6/, and pushed up the v0.1.6 tag.
